# Generated by Django 4.1.2 on 2022-10-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='FeedbackModel',
        ),
    ]
