# Generated by Django 4.1.2 on 2022-10-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogpostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.CharField(choices=[('LW', 'Low'), ('IM', 'Intermediate'), ('HH', 'High')], default='LW', max_length=2)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('opening', models.TextField()),
                ('main', models.TextField()),
                ('closing', models.TextField()),
            ],
        ),
    ]
