# Generated by Django 4.1.2 on 2022-10-26 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blogpost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LW', 'Low'), ('IM', 'Intermediate'), ('HH', 'High')], default='LW', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='importance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogpost.importance'),
        ),
    ]
