# Generated by Django 4.1.2 on 2022-10-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogpost', '0002_importance_alter_blogpost_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='importance',
            field=models.CharField(choices=[('LW', 'Low'), ('IM', 'Intermediate'), ('HH', 'High')], default='LW', max_length=2),
        ),
        migrations.DeleteModel(
            name='Importance',
        ),
    ]
