# Generated by Django 4.1.2 on 2022-10-28 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogpost', '0003_alter_blogpost_importance_delete_importance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogpost',
            new_name='BlogpostModel',
        ),
    ]
