# Generated by Django 4.1.2 on 2022-10-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogpost', '0004_rename_blogpost_blogpostmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
