# Generated by Django 4.1.2 on 2022-10-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogpost', '0005_alter_blogpostmodel_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostmodel',
            old_name='description',
            new_name='opening',
        ),
        migrations.AddField(
            model_name='blogpostmodel',
            name='closing',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpostmodel',
            name='main',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
