# Generated by Django 4.1.2 on 2022-10-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogpost', '0006_rename_description_blogpostmodel_opening_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
