# Generated by Django 4.1.2 on 2022-10-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='username',
            field=models.TextField(default='carlene', max_length=200),
        ),
    ]
