# Generated by Django 4.1.2 on 2022-10-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='preview',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
